name: planty_connect
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  # api calling
  http: ^0.13.3

  # MMVM architecture
  stacked: ^2.1.8

  # state management
  get: ^4.1.4
  rxdart: ^0.27.1

  build_runner: ^1.10.11

  # firebase
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.0
  firebase_storage: ^8.1.0
  cloud_firestore: ^2.2.0
  firebase_auth: ^1.2.0

  # local push notification
  flutter_local_notifications: ^6.0.0

  # screen & app util
  flutter_screenutil: ^5.0.0+2
  intl: ^0.17.0

  # image & doc picker
  image_picker: ^0.8.0+3
  file_picker: ^3.0.3
  photo_manager: ^1.2.9
  media_picker: ^1.3.5
  flutter_absolute_path: ^1.0.6

  # path prover
  path_provider: ^2.0.2

  # permission handler
  permission_handler:

  # open file from chat
  open_file: ^3.2.1

  # download and cache image
  cached_network_image: ^3.0.0

  # generate http link and launch
  flutter_linkify: ^5.0.2
  url_launcher: ^6.0.7

  # chat pagination
  paginate_firestore: ^1.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/font/Nunito-Bold.ttf
        - asset: assets/font/Nunito-ExtraBold.ttf
          weight: 900
        - asset: assets/font/Nunito-Regular.ttf
        - asset: assets/font/Nunito-SemiBold.ttf
          weight: 500